# Use the official MySQL 8.0 image
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=P@ssw0rd
ENV MYSQL_USER=product_user
ENV MYSQL_PASSWORD=product_user_password
ENV MYSQL_DATABASE=product

# Expose MySQL port
EXPOSE 3306